### ISSUE TITLE
没有指定migrate会导致启动时询问

### ISSUE THREAD

**Issue by scgy5555** [yoyoyohamapi/blog#1]
启动时提示 sails.config.models.migrate没指定 需要选择123
会导致程序等待输入，和grunt命令冲突 整个程序就运行不起来
似乎还跟compileAssets中获取不到grunt对sass的编译命令有关
改了之后正常运行

初学sails，感谢demo分享

**Comment by yoyoyohamapi** [comment]
么么哒。谢谢

**Comment by scgy5555** [comment]
grunt-contrib-compass 需要依赖 compass
通过gem install compass安装后正常

启动报错主要是因为这个原因
然而sails.config.models.migrate没指定也造成了一些特殊现象

整个项目似乎缺少ajax交互的内容

**Comment by yoyoyohamapi** [comment]
嗯，ajax太多支持了，觉得不会是问题。本人还是学习，最近项目压力大，之后有空我会继续更新，谢谢
