### ISSUE TITLE
如何在sails中使用redis?

### ISSUE THREAD

**Issue by scgy5555** [yoyoyohamapi/blog#2]
我希望在sails中将redis作为一个services，缓存我需要的内容
通过connections.js设置的redis是否可以直接操作？
或者sails中是否有其他操作redis数据库的方案而不通过orm

**Comment by yoyoyohamapi** [comment]
node怎么操纵，sails就怎么操纵，你新建一个service，里面require node redis就行了，如果要自动连接这些操作，bootstrap里面可以写配置
